### ISSUE TITLE
RevB SD card insertion resets USB comms

### ISSUE THREAD

**Issue by MarkJB** [MarkJB/ESP32_Plotter_Controller#8]
When plugging in an SD card the serial comms disconnect. The ESP32 appears to continue running and the SD card can be read in the webui.

Have added more decoupling but that hasn't worked.

I'm a bit stumpped about this one.

**Comment by MarkJB** [comment]
From vscode serial monitor when inserting an SD card:


```
--- Miniterm on COM9  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ok
ok
Exception in thread rx:
Traceback (most recent call last):
  File "C:\Users\mark\.platformio\python3\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\mark\.platformio\python3\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mark\.platformio\penv\lib\site-packages\serial\tools\miniterm.py", line 499, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "C:\Users\mark\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 295, in read
    raise SerialException("GetOverlappedResult failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: GetOverlappedResult failed (PermissionError(13, 'Access is denied.', None, 5))
```
